name: API 테스트

on:
  workflow_dispatch:
    inputs:
      item_name:
        description: '테스트할 아이템 이름'
        required: true
        default: '빛의 가루'

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: API 호출 테스트
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ITEM_NAME: ${{ github.event.inputs.item_name }}
        run: |
          ENCODED_NAME=$(echo "정령 형상변환 리큐르($ITEM_NAME)" | jq -s -R -r @uri)
          echo "테스트 아이템: 정령 형상변환 리큐르($ITEM_NAME)"
          echo "인코딩된 이름: $ENCODED_NAME"
          
          echo "API 호출 시작..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -X GET \
            "https://open.api.nexon.com/mabinogi/v1/auction/list?auction_item_category=%EA%B8%B0%ED%83%80%20%EC%86%8C%EB%AA%A8%ED%92%88&item_name=$ENCODED_NAME" \
            -H "accept: application/json" \
            -H "x-nxopen-api-key: $API_KEY")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP 응답 코드: $HTTP_CODE"
          echo "응답 본문:"
          echo "$BODY" | jq '.'
