# .github/workflows/collect-data.yml
name: 마비노기 경매장 데이터 수집

on:
  schedule:
    # 매일 오후 6시(KST) = UTC 09:00
    - cron: '0 9 * * *'
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 의존성 설치
        run: npm install
      
      - name: API 테스트
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node test-api.js
      
      - name: 데이터 수집 실행
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node index.js
      
      - name: 변경사항 커밋 및 푸시
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git diff --staged --quiet || git commit -m "데이터 갱신: $(date +'%Y-%m-%d %H:%M')"
          git push
