# .github/workflows/collect-data.yml
name: 마비노기 경매장 데이터 수집

on:
  schedule:
    # 매일 오후 6시(KST) = UTC 09:00
    - cron: '0 9 * * *'
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 의존성 설치
        run: npm install
      
      - name: 데이터 수집 실행
        env:
          API_KEY: ${{ secrets.API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: node src/index.js
      
      # 이전에 생성된 카테고리 JSON 파일 보존
      - name: 데이터 디렉토리 확인
        run: |
          mkdir -p data
          mkdir -p data/database
          
          # 카테고리 데이터가 없으면 생성
          if [ ! -f data/categories.json ]; then
            cp src/category-manager.js /tmp/category-manager.js
            node -e "
              const fs = require('fs');
              const catManager = require('/tmp/category-manager.js');
              
              const data = {
                mainCategories: catManager.mainCategories,
                categories: catManager.categories
              };
              
              fs.writeFileSync('data/categories.json', JSON.stringify(data, null, 2));
              console.log('카테고리 데이터 생성 완료');
            "
          fi
      
      - name: 변경사항 커밋 및 푸시
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git diff --staged --quiet || git commit -m "데이터 갱신: $(date +'%Y-%m-%d %H:%M')"
          git push
